---
title: "Replication of Experiment 1A by Young & Saxe (2011, Cognition)"
author: "Kexin Jiang (k3jiang@ucsd.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  html:
    toc: true
    toc_depth: 3
editor: 
  markdown: 
    wrap: sentence
---

## Introduction

The study investigated the causal effect of agents' intent on moral judgment.
It hypothesized that there are distinct moral domains---harm and purity---in which the agent's innocent intention matters more for the former and less for the latter.
Experiment 1A directly examines this hypothesis.
The results supported it, showing that purity violations were judged morally worse than harm when both were committed accidentally, while harm was judged worse than purity violations when both were committed intentionally.
I chose this study because I have a strong interest in social cognition.
Theoretically, the study emphasizes how intent influences our understanding of others' actions, which I find both fascinating and significant for the field.
Practically, it serves as a great example of how to uncover distinct cognitive signatures across different domains by manipulating key factors.

This is a between-subjects experiment with six conditions consisting of two factors: intent (intentional vs. accidental) and moral domain (harm vs. incest vs. ingestion).
To replicate this experiment, we will collect data from Prolific.
During the experiment, participants will first read moral scenarios in the second person tense (e.g., "Your cousin comes over for dinner", provided in the supplementary materials).
Then, they will rate the moral wrongness of the action on a 7-point scale, anchored at "not at all morally wrong" (1) to "very morally wrong" (7).
For each moral domain, there are two scenarios: harm (allergy, poison), incest (parent, sibling), and ingestion (dog meat, urine).
Each scenario has two versions (intentional and accidental), and each participant will see only one version.

The challenge in replicating this experiment might be a lack of experience in collecting online data from Prolific.
I hope I can manage the materials counterbalancing right.
I will learn a lot.

[Link to the original paper](https://www.sciencedirect.com/science/article/pii/S0010027711001107#s0010)

[Link to the repository](https://github.com/KexinJiang27/Replication-of-Experiment-1A-by-Young-Saxe-2011-Cognition)

## Methods

### Power Analysis

This paper uses Partial η² as a measure of effect size in ANOVA. We will calculate it as well.

### Planned Sample

We can replicate the sample size from the paper, targeting approximately 262 participants.

We will screen out repeat participants using the same exclusion criteria as in the original paper: excluding individuals who have previously taken a similar survey and eliminating data from participants with identical prolific IDs.

### Materials

Each participant made a moral judgment for a single scenario.
Participants were assigned randomly to one of six conditions in a 2 (intentional versus accidental) × 3 (harm versus incest versus ingestion) between-subjects experimental design.
Here are the materials to present to participants.

**Harm**

-   Allergy - Intentional: Imagine your cousin is over for dinner. You know she is allergic to peanuts. You decide to add peanuts to the dish because they really bring out the flavor for you. You grind up the peanuts, add them in, and serve your cousin.
-   Allergy - Accidental: Imagine your cousin is over for dinner. You have no idea she is allergic to peanuts. You decide to add peanuts to the dish because they really bring out the flavor for you. You grind up the peanuts, add them in, and serve your cousin.
-   Poison - Intentional: Imagine you and a co-worker are taking a tour of a chemical plant. During the coffee break, you go to pour some coffee. You like yours black, but your co-worker asks for sugar in hers. You spoon some powder into your co-worker's coffee. You know full well that you are putting poison in her coffee.
-   Poison - Accidental: Imagine you and a co-worker are taking a tour of a chemical plant. During the coffee break, you go to pour some coffee. You like yours black, but your co-worker asks for sugar in hers. You spoon some powder into your co-worker's coffee. You do not know that someone replaced the sugar with poison.

**Incest**

-   Sibling - Intentional: Imagine you are at a dorm party and really hit it off with someone. This person feels the same way about you. That night, you end up talking, and you discover that you are actually long lost siblings. At the end of the night, you decide to sleep together (using two forms of birth control to be safe).
-   Sibling - Accidental: Imagine you are at a dorm party and really hit it off with someone. This person feels the same way about you. At the end of the night, you decide to sleep together (using two forms of birth control to be safe). The next day, you end up talking, and you discover that you are actually long lost siblings.
-   Parent - Intentional: Imagine you were adopted at birth - you have never met your birth parents. The weekend of your college reunion, you go to your school's football game and meet someone a bit older. You discover that this person is actually your biological parent. You two get along really well and, that night, end up sleeping together (using two forms of birth control to be safe). Parent - Accidental: Imagine you were adopted at birth - you have never met your birth parents. The weekend of your college reunion, you go to your school's football game and meet someone a bit older. You have no idea that this person is actually your biological parent. You two get along really well and, that night, end up sleeping together (using two forms of birth control to be safe).

**Ingestion**

-   Dog - Intentional: Imagine that a car just killed your beloved dog. Your significant other has heard that dog meat is delicious and freezes the meat of your dog before it goes bad. Later, you decide to make yourself dinner. You see a package in the freezer. It is correctly labeled "dog". You end up eating your dog for dinner.
-   Dog - Accidental: Imagine that a car just killed your beloved dog. Your significant other has heard that dog meat is delicious and freezes the meat of your dog before it goes bad. Later, you decide to make yourself dinner. You see a package in the freezer. It is incorrectly labeled "beef" -- but it is actually the meat from your dog. Without realizing it, you end up eating your dog for dinner.
-   Urine - Intentional: Imagine that you are waiting to brush your teeth while your friend is in the bathroom. As she leaves, you notice a cup and a pregnancy test. Your friend warns you that the cup contains her urine for her pregnancy test. You finish brushing your teeth and use that cup to rinse out your mouth.
-   Urine -- Accidental: Imagine that you are waiting to brush your teeth while your friend is in the bathroom. As she leaves, you notice a cup and a pregnancy test. Your friend forgets to tell you that the cup contains her urine for her pregnancy test. You finish brushing your teeth and use that cup to rinse out your mouth.

### Procedure

Moral scenarios were presented to participants. Participants judged the moral wrongness of the action, on a 7-point scale anchored at "not at all morally wrong" (1) to "very morally wrong" (7).
Two scenarios represented each domain: harm (allergy, poison), incest (parent, sibling) or ingestion (dog meat, urine). There were two versions of each scenario (intentional, accidental); each participant saw only one version.


### Analysis Plan

We will replicate Experiment 1A from the original study. Before analysis, we will screen out repeat participants.

Our dependent variable will be the moral judgments made by participants on a 7-point scale.

First, to verify that judgments of the two stories representing each violation type did not differ, we will conduct three 2 (story) × 2 (intent) ANOVAs: for harm, incest, and ingestion.

If we replicate the findings of no main effect of story and no story-by-intent interaction, we will proceed with three 2 (intent) × 2 (domain) ANOVAs. This will be the key analysis of this study, allowing us to compare the role of intent in the following pairings: (1) harm versus incest, (2) harm versus ingestion, and (3) incest versus ingestion.

If any significant interaction effects are found, we will further conduct independent-samples t-tests to identify specific difference patterns, following the approach of the original paper. .


### Differences from Original Study

The only difference may arise from the different participant samples. Additionally, we collect data from two platforms (Prolific vs. MTurk), and participants on these platforms may have different characteristics.


### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample

Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan

Any differences from what was described as the original plan, or "none".

## Results

### Data preparation

Data preparation following the analysis plan.

```{r data preparation}
### Data Preparation

#### Load Relevant Libraries and Functions
#library(tidyr)
#library(dplyr)
#library(ggplot2)


#### Import data
#raw_data = read.csv("/data/data.csv")

#### Data exclusion / filtering

# exclude subs that took similar survey before
# filetered_data = raw_data %>% 
#  filter(is.na(TakeSurveyBefore))

# exclude duplicated prolfic ids
# cleaned_data = filetered_data %>% 
#  distinct(prolific_id, .keep_all = TRUE)

#### Prepare data for analysis - create columns etc.

# create columns for all variables in a dataframe from cleaned_data
# convert wide data into long data for analysis and visualization

```

### Confirmatory analysis

We will replicate Experiment 1A from the original study. Before analysis, we will screen out repeat participants.

Our dependent variable will be the moral judgments made by participants on a 7-point scale.

First, to verify that judgments of the two stories representing each violation type did not differ, we will conduct three 2 (story) × 2 (intent) ANOVAs: for harm, incest, and ingestion.

If we replicate the findings of no main effect of story and no story-by-intent interaction, we will proceed with three 2 (intent) × 2 (domain) ANOVAs, allowing us to compare the role of intent in the following pairings: (1) harm versus incest, (2) harm versus ingestion, and (3) incest versus ingestion.

If any significant interaction effects are found, we will further conduct independent-samples t-tests to identify specific difference patterns, following the approach of the original paper. 

This is the key analysis of this study.

If we replicate the original findings, we expect to see a significant main effect for both intent and domain in all three ANOVAs, with only a significant intent-by-domain interaction in the first two ANOVAs, but not in the last.

Ultimately, we aim to confirm that innocent intent plays a greater role in moral judgments of harm versus purity violations. Specifically, we anticipate that accidental harms will be judged as less morally wrong than accidental purity violations,though harms were not judged less morally wrong than purity violations in general.


### Exploratory analyses

Any follow-up analyses desired (not required).

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.
None of these need to be long.
