<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Cassie Wang (tiw037@ucsd.edu)">
<meta name="dcterms.date" content="2024-12-06">

<title>Replication of Study by Young &amp; Saxe. (2011, Cognition)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="writeup_cassiewang_files/libs/clipboard/clipboard.min.js"></script>
<script src="writeup_cassiewang_files/libs/quarto-html/quarto.js"></script>
<script src="writeup_cassiewang_files/libs/quarto-html/popper.min.js"></script>
<script src="writeup_cassiewang_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="writeup_cassiewang_files/libs/quarto-html/anchor.min.js"></script>
<link href="writeup_cassiewang_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="writeup_cassiewang_files/libs/quarto-html/quarto-syntax-highlighting-29e2c20b02301cfff04dc8050bf30c7e.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="writeup_cassiewang_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="writeup_cassiewang_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="writeup_cassiewang_files/libs/bootstrap/bootstrap-e19dc0c07aeef78048e587c3f1edba7a.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#experimental-paradigam" id="toc-experimental-paradigam" class="nav-link active" data-scroll-target="#experimental-paradigam">Experimental paradigam:</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#design-oveview" id="toc-design-oveview" class="nav-link" data-scroll-target="#design-oveview">Design Oveview</a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods">Methods</a>
  <ul class="collapse">
  <li><a href="#power-analysis" id="toc-power-analysis" class="nav-link" data-scroll-target="#power-analysis">Power Analysis</a></li>
  <li><a href="#planned-sample" id="toc-planned-sample" class="nav-link" data-scroll-target="#planned-sample">Planned Sample</a></li>
  <li><a href="#materials" id="toc-materials" class="nav-link" data-scroll-target="#materials">Materials</a></li>
  <li><a href="#procedure" id="toc-procedure" class="nav-link" data-scroll-target="#procedure">Procedure</a></li>
  <li><a href="#analysis-plan" id="toc-analysis-plan" class="nav-link" data-scroll-target="#analysis-plan">Analysis Plan</a></li>
  <li><a href="#differences-from-original-study" id="toc-differences-from-original-study" class="nav-link" data-scroll-target="#differences-from-original-study">Differences from Original Study</a></li>
  <li><a href="#methods-addendum-post-data-collection" id="toc-methods-addendum-post-data-collection" class="nav-link" data-scroll-target="#methods-addendum-post-data-collection">Methods Addendum (Post Data Collection)</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#data-preparation" id="toc-data-preparation" class="nav-link" data-scroll-target="#data-preparation">Data preparation</a></li>
  <li><a href="#confirmatory-analysis" id="toc-confirmatory-analysis" class="nav-link" data-scroll-target="#confirmatory-analysis">Confirmatory analysis</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a>
  <ul class="collapse">
  <li><a href="#summary-of-replication-attempt" id="toc-summary-of-replication-attempt" class="nav-link" data-scroll-target="#summary-of-replication-attempt">Summary of Replication Attempt</a></li>
  <li><a href="#commentary" id="toc-commentary" class="nav-link" data-scroll-target="#commentary">Commentary</a></li>
  <li><a href="#contribution" id="toc-contribution" class="nav-link" data-scroll-target="#contribution">Contribution</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Replication of Study by Young &amp; Saxe. (2011, Cognition)</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Cassie Wang (tiw037@ucsd.edu) </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 6, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="experimental-paradigam" class="level3">
<h3 class="anchored" data-anchor-id="experimental-paradigam">Experimental paradigam:</h3>
<p>https://ucsd-psych201a.github.io/young2011/</p>
<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Moral judgments are often shaped by the perceived intentions behind actions. Prior research, including a study by Young and Saxe (2011) (https://doi.org/10.1016/j.cognition.2011.04.005), suggests that the importance of intent varies across different moral domains. For instance, harmful actions tend to be judged more heavily based on the actor’s intentions, while purity violations—such as incest or consuming taboo substances—are often viewed as wrong regardless of intent. This difference aligns with theories of moral foundations, which associate purity violations with strong disgust reactions and harm violations with greater attention to the actor’s mental state.</p>
<p>The key question in the original study was whether intent plays a greater role in moral judgments of harm compared to purity. The results revealed a significant interaction between moral domain and intent: harm judgments were highly sensitive to intent, while purity violations (involving incest and ingestion) were less so. For example, accidental harm was judged as less wrong than accidental purity violations, whereas intentional harm was seen as more wrong than intentional purity violations.</p>
<p>In this replication study, we revisited the role of intent in moral judgments across three domains: harm, incest, and ingestion. We closely followed the original study’s design, using second-person scenarios and a 7-point moral wrongness scale. Our goal was to test the robustness of the original findings in a new sample and recruitment platform while exploring whether cultural or methodological differences might influence the results.</p>
</section>
<section id="design-oveview" class="level2">
<h2 class="anchored" data-anchor-id="design-oveview">Design Oveview</h2>
<p>We used a 2 (intent: intentional vs.&nbsp;accidental) × 3 (domain: harm, incest, ingestion) between-subjects design. Participants were randomly assigned to read one scenario that varied by both intent and domain. After reading the scenario, they rated the moral wrongness of the action on a 7-point scale, ranging from “not at all morally wrong” to “very morally wrong.” Our study closely followed the original design, with the primary difference being the use of Prolific for participant recruitment instead of Amazon MTurk.</p>
<p>To preserve the integrity of the study, we maintained the original between-subjects design. A within-subjects design could have led participants to guess the study’s purpose, potentially influencing their responses. The experiment was conducted double-blind. Although factors such as cultural background, religious beliefs, education level, and gender could influence moral judgments, these variables were not explicitly manipulated in our study.</p>
</section>
<section id="methods" class="level2">
<h2 class="anchored" data-anchor-id="methods">Methods</h2>
<section id="power-analysis" class="level3">
<h3 class="anchored" data-anchor-id="power-analysis">Power Analysis</h3>
<p>Based on a conventional medium-large effect size (Cohen’s d ~ 0.8) and aiming for 80% power at α = .05, a sample size of approximately 351 participants was deemed sufficient. Feasibility considerations led us to target a similar sample size. Our final analyzed sample included 343 participants, closely matching the power requirements.</p>
</section>
<section id="planned-sample" class="level3">
<h3 class="anchored" data-anchor-id="planned-sample">Planned Sample</h3>
<p>We recruited English-speaking adults living in the United States through Prolific. We included participants aged 18-100, aiming for a diverse demographic. Given our power analysis, we planned to collect around 351 participants; the final sample included 343 usable responses. Participants who indicated that they had completed a similar task before were excluded to prevent familiarity biases.</p>
</section>
<section id="materials" class="level3">
<h3 class="anchored" data-anchor-id="materials">Materials</h3>
<p>We used the same moral judgment scenarios as in the original study, adapted in the second-person perspective. Scenarios fell into three domains: - Harm (e.g., poisoning or unknowingly causing an allergic reaction) - Incest (e.g., a sexual relationship between siblings) - Ingestion (e.g., consuming taboo substances, like dog meat or urine) Each scenario had intentional and accidental versions. For instance, in an accidental harm scenario, a participant (you) inadvertently causes harm due to ignorance of a critical detail (e.g., peanut allergy).</p>
</section>
<section id="procedure" class="level3">
<h3 class="anchored" data-anchor-id="procedure">Procedure</h3>
<p>Participants were randomly assigned to one of the six conditions (2 intent levels × 3 domains) and presented with a single scenario. After reading it, they provided a moral wrongness rating on a scale from 1 (“not at all morally wrong”) to 7 (“very morally wrong”). The survey was administered online, and participants were compensated for their time.</p>
</section>
<section id="analysis-plan" class="level3">
<h3 class="anchored" data-anchor-id="analysis-plan">Analysis Plan</h3>
<p>We planned to conduct a series of ANOVAs to examine the intent × domain interaction. First, we would test whether different story exemplars within the same domain differed significantly. If no differences emerged, we would collapse across exemplars. Then, we would conduct 2 (intent) × 2 (domain) comparisons to replicate the original analyses, focusing on the role of intent in harm vs.&nbsp;purity (incest, ingestion) judgments.</p>
<p>We expected to replicate the original findings: intent would have a stronger effect on harm judgments compared to purity judgments. Specifically, accidental harm should be judged less harshly than accidental purity violations, while intentional harm should be judged more harshly than intentional purity violations.</p>
</section>
<section id="differences-from-original-study" class="level3">
<h3 class="anchored" data-anchor-id="differences-from-original-study">Differences from Original Study</h3>
<p>The original study recruited participants via Amazon Mechanical Turk, while we used Prolific. Although both platforms host English-speaking U.S. participants, minor demographic differences might exist. We adhered to similar exclusion criteria and closely matched the original methods otherwise. We believe these minor methodological shifts are unlikely to significantly alter the core patterns of results.</p>
</section>
<section id="methods-addendum-post-data-collection" class="level3">
<h3 class="anchored" data-anchor-id="methods-addendum-post-data-collection">Methods Addendum (Post Data Collection)</h3>
<section id="actual-sample" class="level4">
<h4 class="anchored" data-anchor-id="actual-sample">Actual Sample</h4>
<p>We collected 343 participants, all English-speaking adults residing in the United States. The sample size was slightly below the targeted 351 but still provided sufficient power.</p>
</section>
<section id="differences-from-pre-data-collection-methods-plan" class="level4">
<h4 class="anchored" data-anchor-id="differences-from-pre-data-collection-methods-plan">Differences from pre-data collection methods plan</h4>
<p>No major deviations from our preregistered plan occurred.</p>
</section>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<section id="data-preparation" class="level3">
<h3 class="anchored" data-anchor-id="data-preparation">Data preparation</h3>
<p>Data preparation following the analysis plan.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>AOV comparing harm vs. incest</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                  Df Sum Sq Mean Sq F value   Pr(&gt;F)    
domain             1   10.2    10.2   2.371 0.125055    
intention          1  394.1   394.1  91.238  &lt; 2e-16 ***
domain:intention   1   54.6    54.6  12.648 0.000462 ***
Residuals        216  933.1     4.3                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
AOV comparing harm vs. ingestion</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                  Df Sum Sq Mean Sq F value   Pr(&gt;F)    
domain             1    4.5    4.50   1.105    0.294    
intention          1  230.5  230.48  56.638 8.92e-13 ***
domain:intention   1  169.0  169.04  41.539 5.70e-10 ***
Residuals        256 1041.7    4.07                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
AOV comparing incest vs. ingestion</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                  Df Sum Sq Mean Sq F value   Pr(&gt;F)    
domain             1   26.8   26.81   5.983 0.015225 *  
intention          1   59.5   59.46  13.269 0.000336 ***
domain:intention   1   17.7   17.71   3.953 0.048022 *  
Residuals        222  994.8    4.48                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Mean Ratings and Standard Errors:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  domain    intention   mean_rating se_rating
  &lt;fct&gt;     &lt;fct&gt;             &lt;dbl&gt;     &lt;dbl&gt;
1 harm      accidental        0.481     0.124
2 harm      intentional       4.74      0.220
3 incest    accidental        2         0.413
4 incest    intentional       3.88      0.273
5 ingestion accidental        3.78      0.265
6 ingestion intentional       4.42      0.237</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="writeup_cassiewang_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="confirmatory-analysis" class="level3">
<h3 class="anchored" data-anchor-id="confirmatory-analysis">Confirmatory analysis</h3>
<p>The original study by Young and Saxe (2011) found that:</p>
<ol type="1">
<li><p>There were no significant differences between stories within each domain. Each of the three 2 (story) × 2 (intent) ANOVAs (for harm, incest, and ingestion) revealed main effects of intent but not story, and no story × intent interaction. This allowed the original authors to collapse across stories within each domain in subsequent analyses.</p></li>
<li><p>When comparing harm to incest and harm to ingestion using 2 (intent) × 2 (domain) ANOVAs, the original results showed a significant intent × domain interaction. This indicated that intent mattered more for harm judgments than for purity (incest, ingestion). Specifically, accidental purity violations were judged more morally wrong than accidental harm, and intentional harm was judged more morally wrong than intentional purity violations, aligning with the predicted difference in how intent influences moral judgments of harm versus purity.</p></li>
<li><p>However, when comparing the two purity domains (incest vs.&nbsp;ingestion), the original study found no intent × domain interaction. Both forms of purity violations were judged similarly in terms of intent-sensitivity, suggesting that purity as a category was less intent-dependent than harm.</p></li>
</ol>
<p>In contrast, our replication found:</p>
<ul>
<li><p>Similar to the original, we found main effects of intent in all comparisons, indicating that intentional violations are judged more harshly than accidental ones in general.</p></li>
<li><p>In comparisons of harm versus incest and harm versus ingestion, we also replicated the pattern of significant domain × intent interactions. This suggests that, as originally reported, harm judgments remain more intent-sensitive than purity judgments.</p></li>
<li><p>Critically, our replication diverged from the original findings when comparing incest versus ingestion. While the original study reported no domain × intent interaction for the two purity domains, our results indicated a significant interaction (F(1, 222) = 3.95, p = 0.048). In other words, unlike the original study, we found that the two purity domains (incest and ingestion) were not equally insensitive to intent; instead, we observed subtle differences in how intent influenced judgments within these purity scenarios.</p></li>
</ul>
<p>In terms of mean ratings, our results also showed a somewhat different pattern than the original. The original study highlighted that accidental purity violations (incest and ingestion) were judged more harshly than accidental harm, while intentional harm was judged more harshly than purity violations. Our mean ratings suggest a similar pattern for harm vs.&nbsp;incest and harm vs.&nbsp;ingestion (with accidental purity &gt; accidental harm and intentional harm &gt; intentional purity). However, the difference between the two purity domains themselves was more pronounced in our data: accidental incest (M = 2.00) and accidental ingestion (M = 3.78) differed notably, indicating that not all purity violations are treated identically with respect to accidental intent.</p>
</section>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<section id="summary-of-replication-attempt" class="level3">
<h3 class="anchored" data-anchor-id="summary-of-replication-attempt">Summary of Replication Attempt</h3>
<p>Our replication partially diverged from the original findings. While we replicated the general notion that intent matters for moral judgment, we did not confirm the original pattern of intent playing a significantly larger role only for harm. Instead, our results suggest that differences in how intent affects judgments extended to within the purity domain comparisons as well.</p>
</section>
<section id="commentary" class="level3">
<h3 class="anchored" data-anchor-id="commentary">Commentary</h3>
<p>Several factors could explain this discrepancy. Slight differences in participant demographics, cultural shifts since the original study, or the use of a different recruitment platform (Prolific vs.&nbsp;MTurk) may have influenced how participants evaluated purity-related scenarios. Also, given the passing of time and changes in cultural norms, what was once seen as uniformly taboo (and thus less sensitive to intent) may now be interpreted with more nuance.</p>
<p>The expanded effect of intent in purity domains could indicate that the originally reported pattern was not as stable or universal as presumed. Alternatively, our larger sample (343 participants) may have provided more statistical power, detecting subtle differences that the original study’s sample missed. Another possibility is that exposure to more varied moral content online has sensitized participants to consider mental states even in purity violations.</p>
<p>In future research, including measures of disgust sensitivity, moral foundations, or other individual difference variables may help explain why purity domains may now be showing increased intent sensitivity. Further replications could clarify whether these shifts are due to methodological differences, cultural change over time, or random sampling variation.</p>
<p>In conclusion, although we followed the original methodology closely, our replication did not yield identical results. This outcome highlights the importance of replication in moral psychology research and the necessity of considering cultural and temporal contexts when interpreting moral judgments.</p>
</section>
<section id="contribution" class="level3">
<h3 class="anchored" data-anchor-id="contribution">Contribution</h3>
<p>Conceptualization: Coxi Jiang, Belynda Herrera, Seyi Lawal, and Cassie Wang. Data curation: Coxi Jiang, Belynda Herrera, Seyi Lawal, and Cassie Wang. Formal analysis: Coxi Jiang and Seyi Lawal. Funding acquisition: Coxi Jiang, Belynda Herrera, Seyi Lawal, and Cassie Wang. Investigation: Coxi Jiang, Belynda Herrera, Seyi Lawal, and Cassie Wang. Methodology: Coxi Jiang, Belynda Herrera, Seyi Lawal, and Cassie Wang. Software: Coxi Jiang and Seyi Lawal. Visualization: Coxi Jiang and Seyi Lawal. Writing - original draft: Coxi Jiang, Belynda Herrera, Seyi Lawal, and Cassie Wang. Writing - review &amp; editing: Coxi Jiang, Belynda Herrera, Seyi Lawal, and Cassie Wang.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>